services:
  backend:
    container_name: bets-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - SERVER_PORT=${SERVER_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
    networks:
      - postgres-connection
  frontend:
    container_name: bets-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend

networks:
  postgres-connection:
    external: true