services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      # The volume to store the database data
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local